-- SWOT analyses finales (correction syntaxe)
INSERT INTO swot_analyses (scenario_id, analysis_type, strengths, weaknesses, opportunities, threats) VALUES
('kpi-performance', 'company', '{"growth": "Croissance 200% annuelle", "product": "Produits tendance", "digital": "Expertise digital native"}', '{"attribution": "Attribution complexe", "budget": "Budgets marketing dispersés", "data": "Données silos"}', '{"omnichannel": "Stratégie omnicanale", "international": "Expansion Europe", "ai": "Personnalisation IA"}', '{"competition": "Pure players", "costs": "Inflation acquisition", "economy": "Ralentissement économique"}'),

('digital-agency', 'product', '{"specialization": "Spécialisé agences", "ux": "Interface intuitive", "automation": "Automatisations avancées"}', '{"price": "Prix premium", "complexity": "Fonctionnalités nombreuses", "market": "Marché niche"}', '{"growth": "Croissance agences", "remote": "Travail hybride", "ai": "IA workflows"}', '{"giants": "HubSpot/Salesforce", "economy": "Récession agences", "saturation": "Marché saturé"}'),
('digital-agency', 'company', '{"team": "Équipe talentueuse", "growth": "Croissance rapide", "reputation": "Bonne réputation"}', '{"crm": "CRM obsolète", "processes": "Processus manuels", "time": "Temps admin élevé"}', '{"scale": "Scaling rapide", "clients": "Nouveaux clients", "services": "Nouveaux services"}', '{"competition": "Agences concurrentes", "talent": "Rétention talents", "costs": "Inflation coûts"}'),

('fintech-startup', 'product', '{"precision": "Précision 98.5%", "speed": "API sub-100ms", "ai": "IA propriétaire"}', '{"cost": "Coût développement", "complexity": "Complexité technique", "regulation": "Conformité stricte"}', '{"fintech": "Boom fintech", "regulation": "Open banking", "ai": "IA explicable"}', '{"regulation": "Durcissement réglementaire", "bias": "Biais algorithmiques", "competition": "BigTech fintech"}'),
('fintech-startup', 'company', '{"innovation": "Innovation constante", "team": "Équipe de pointe", "growth": "Croissance 400%"}', '{"scoring": "Scoring basique", "defaults": "Taux défaut élevé", "competition": "Retard concurrentiel"}', '{"funding": "Levée fonds", "partnerships": "Partenariats banques", "international": "Expansion internationale"}', '{"regulation": "Régulation IA", "competition": "Concurrence accrue", "economy": "Ralentissement crédit"}'),

('manufacturing-iot', 'product', '{"industry40": "Expertise industrie 4.0", "predictive": "IA prédictive", "security": "Sécurité industrielle"}', '{"cost": "Investissement important", "complexity": "Complexité déploiement", "maintenance": "Maintenance spécialisée"}', '{"industry40": "Industrie 4.0", "sustainability": "Durabilité", "automation": "Automatisation"}', '{"cyber": "Cyberattaques industrielles", "economy": "Ralentissement industriel", "skills": "Pénurie compétences"}';