-- Finalisation enrichissement tous scénarios - Produits restants
INSERT INTO products (scenario_id, name, description, pricing_starter, pricing_professional, pricing_enterprise, key_features, competitive_advantages, roi, implementation_time) VALUES
('kpi-performance', 'ModaAnalytics Pro', 'Plateforme analytics e-commerce avec attribution multi-canal avancée', '€400/mois - Jusqu''à 100k sessions', '€1,200/mois - Jusqu''à 1M sessions', '€3,500/mois - Illimité + IA prédictive', ARRAY['Attribution multi-canal', 'Analytics temps réel', 'Prédictions IA', 'Intégrations 50+ outils', 'Rapports automatisés', 'API complète'], ARRAY['Spécialisation e-commerce', 'IA attribution propriétaire', 'Support FR expert', 'ROI prouvé +45%'], '+45% ROI marketing, -30% CAC, +25% LTV', '2-3 semaines'),
('digital-agency', 'AgencyFlow CRM', 'CRM nouvelle génération spécialement conçu pour agences digitales', '€50/utilisateur/mois - Jusqu''à 10 users', '€80/utilisateur/mois - Jusqu''à 50 users', '€120/utilisateur/mois - Illimité + IA', ARRAY['Gestion projets intégrée', 'Facturation automatisée', 'Reporting client temps réel', 'Gestion équipe', 'Pipeline automatisé', 'App mobile'], ARRAY['Spécialisé agences', 'Interface intuitive', 'Automatisations avancées', 'Support expert agences'], '+40% productivité, +60% rétention client, -50% admin', '1-2 semaines'),
('fintech-startup', 'CreditAI Engine', 'Moteur IA prédictive pour scoring crédit nouvelle génération', '€5,000/mois - 1000 scorings', '€15,000/mois - 10k scorings', '€35,000/mois - Illimité + ML custom', ARRAY['IA deep learning', 'Scoring temps réel', 'APIs RESTful', 'Monitoring biais', 'Explicabilité IA', 'Conformité RGPD'], ARRAY['Précision 98.5%', 'Réduction biais 85%', 'API sub-100ms', 'Expertise fintech'], '+35% précision scoring, -60% défauts, +25% profitabilité', '4-6 semaines'),
('manufacturing-iot', 'IndustryConnect IoT', 'Plateforme IoT industrielle pour maintenance prédictive et optimisation', '€2,500/mois - 100 capteurs', '€7,500/mois - 500 capteurs', '€18,000/mois - Illimité + IA avancée', ARRAY['Capteurs IoT industriels', 'Maintenance prédictive', 'Analytics temps réel', 'Alertes intelligentes', 'Intégration ERP/MES', 'Edge computing'], ARRAY['Expertise industrie 4.0', 'IA prédictive propriétaire', 'Sécurité industrielle', 'ROI 300% prouvé'], '+30% efficacité, -40% pannes, -25% coûts maintenance', '8-12 semaines');

-- SWOT analyses finales
INSERT INTO swot_analyses (scenario_id, analysis_type, strengths, weaknesses, opportunities, threats) VALUES
('kpi-performance', 'product', '{"attribution": "Attribution multi-canal avancée", "ai": "IA prédictive propriétaire", "integration": "50+ intégrations"}', '{"price": "Prix premium segment", "complexity": "Courbe apprentissage", "support": "Support français uniquement"}', '{"ecommerce": "Boom e-commerce", "privacy": "Fin cookies tiers", "ai": "IA générative marketing"}', '{"giants": "Google/Meta analytics", "privacy": "Réglementations données", "competition": "Nouveaux entrants"}'),
('kpi-performance', 'company', '{"growth": "Croissance 200% annuelle", "product": "Produits tendance", "digital": "Expertise digital native"}', '{"attribution": "Attribution complexe", "budget": "Budgets marketing dispersés", "data": "Données silos"}', '{"omnichannel": "Stratégie omnicanale", "international": "Expansion Europe", "ai": "Personnalisation IA"}', '{"competition": "Pure players", "costs": "Inflation acquisition", "economy": "Ralentissement économique"}';