-- PHASE A: Nettoyage complet de la base de données

-- 1. Supprimer complètement le scénario byss-vns-school
DELETE FROM interlocutors WHERE scenario_id = 'byss-vns-school';
DELETE FROM products WHERE scenario_id = 'byss-vns-school';
DELETE FROM swot_analyses WHERE scenario_id = 'byss-vns-school';
DELETE FROM stakeholders WHERE scenario_id = 'byss-vns-school';
DELETE FROM scenarios WHERE id = 'byss-vns-school';

-- 2. Garder seulement 1 interlocuteur par scénario (supprimer les autres)
-- Pour chaque scénario, garder celui avec l'ID le plus récent (plus spécifique)
DELETE FROM interlocutors 
WHERE id NOT IN (
  SELECT DISTINCT ON (scenario_id) id 
  FROM interlocutors 
  WHERE scenario_id != 'byss-vns-school'
  ORDER BY scenario_id, created_at DESC
);

-- 3. Enrichissement massif des données - PHASE C

-- FINTECH STARTUP - Enrichir les produits/services (4-5 détaillés)
INSERT INTO products (scenario_id, name, description, pricing_starter, pricing_professional, pricing_enterprise, key_features, competitive_advantages, roi, technical_specs, market_positioning, target_segments, implementation_time) VALUES
('fintech-startup', 'Platform API Core', 'API de paiement instantané multi-devises avec intelligence artificielle pour la détection de fraudes en temps réel. Permet aux fintechs de traiter 100M+ transactions/jour avec une latence sub-seconde.', '0€/mois + 0.8% par transaction', '500€/mois + 0.6% par transaction', 'Sur devis + 0.4% par transaction', ARRAY['Anti-fraude IA temps réel', 'Multi-devises 150+ pays', 'API RESTful & GraphQL', 'Dashboard analytics avancé', 'Compliance PCI DSS Level 1', 'Webhooks temps réel'], ARRAY['Latence 50ms vs 200ms concurrents', 'Taux de faux positifs fraude <0.1%', 'Support 24h/7j en français', 'Intégration en 2 lignes de code'], 'ROI 340% en 18 mois, réduction 60% coûts fraude', '{"compliance": ["PCI DSS", "PSD2", "GDPR"], "performance": "100M req/day", "availability": "99.99%", "latency": "<50ms"}', '{"category": "Core Infrastructure", "positioning": "Premium API-first", "target_market": "Fintech scale-ups"}', ARRAY['Néobanques', 'Marketplaces', 'Fintechs B2B'], '2-3 semaines');

INSERT INTO products (scenario_id, name, description, pricing_starter, pricing_professional, pricing_enterprise, key_features, competitive_advantages, roi) VALUES
('fintech-startup', 'Credit Scoring Engine', 'Moteur de scoring crédit nouvelle génération utilisant +2000 variables et machine learning pour évaluer le risque en temps réel sur des profils non-bancarisés.', '2000€/mois', '8000€/mois', '25000€/mois', ARRAY['ML scoring 2000+ variables', 'API temps réel <100ms', 'Dashboard risk management', 'Monitoring portefeuille', 'Alerts automatiques'], ARRAY['Précision 94% vs 78% scores traditionnels', 'Couverture profils thin-file', 'Réduction 45% défauts de paiement'], 'Réduction 45% pertes crédit, +60% approbations profils valides'),
('fintech-startup', 'KYC Automation Suite', 'Suite complète d''automatisation KYC/AML avec reconnaissance faciale, vérification documents, et screening listes sanctions en temps réel.', '1500€/mois', '5000€/mois', '15000€/mois', ARRAY['Reconnaissance faciale biométrique', 'OCR documents 190+ pays', 'Screening sanctions temps réel', 'Workflow personnalisable', 'Rapports compliance'], ARRAY['Traitement 95% dossiers automatique', 'Temps vérification <30 secondes', 'Taux faux positifs <2%'], 'Réduction 80% temps onboarding, -70% coûts compliance'),
('fintech-startup', 'Treasury Management Platform', 'Plateforme de gestion de trésorerie multi-entités avec prévisions IA, optimisation liquidité et gestion risque change automatisée.', '3000€/mois', '10000€/mois', 'Sur devis', ARRAY['Prévisions trésorerie IA', 'Optimisation liquidité automatique', 'Couverture change automatisée', 'Reporting réglementaire', 'API bancaires'], ARRAY['Précision prévisions 96%', 'Optimisation rendement +2.3%', 'Automatisation 90% tâches'], 'Optimisation rendement +2.3%, gain productivité 65%');

-- RETAIL PERSONALIZATION - Créer des produits détaillés
INSERT INTO products (scenario_id, name, description, pricing_starter, pricing_professional, pricing_enterprise, key_features, competitive_advantages, roi) VALUES
('retail-personalization', 'AI Recommendation Engine', 'Moteur de recommandation temps réel utilisant deep learning pour personnaliser l''expérience de 50M+ clients avec +40% conversion.', '2000€/mois', '8000€/mois', '30000€/mois', ARRAY['Deep learning recommandations', 'Temps réel <50ms', 'A/B testing intégré', 'Analytics comportementales', 'API/SDK mobile'], ARRAY['Conversion +42% vs concurrents', 'Temps réel vs batch competitors', 'No-code implementation'], 'ROI 520% en 12 mois, +42% conversion, +35% panier moyen'),
('retail-personalization', 'Dynamic Pricing Platform', 'Plateforme de prix dynamique avec monitoring concurrence temps réel et optimisation marge/volume par IA prédictive.', '1500€/mois', '6000€/mois', '20000€/mois', ARRAY['Pricing IA prédictive', 'Monitoring concurrence automatique', 'Règles métier flexibles', 'Optimisation marge/volume', 'Dashboard temps réel'], ARRAY['Optimisation automatique 24h/7j', 'Réaction concurrence <10min', 'Machine learning pricing'], '+18% marge brute, +25% volume ventes'),
('retail-personalization', 'Customer Journey Analytics', 'Plateforme d''analytics 360° du parcours client omnicanal avec attribution multi-touch et prédiction churn.', '1000€/mois', '4000€/mois', '15000€/mois', ARRAY['Tracking omnicanal', 'Attribution multi-touch', 'Prédiction churn ML', 'Segmentation automatique', 'Campagnes personnalisées'], ARRAY['Vision unifiée online/offline', 'Prédiction churn 92% précision', 'Attribution last-click to multi-touch'], 'Réduction churn 35%, +28% LTV client'),
('retail-personalization', 'Inventory Optimization Suite', 'Suite d''optimisation stock avec prévisions de demande IA, gestion automatique réassorts et optimisation cash flow.', '800€/mois', '3000€/mois', '12000€/mois', ARRAY['Prévisions demande IA', 'Réassorts automatiques', 'Optimisation cash flow', 'Alerts ruptures/surstock', 'Intégration ERP'], ARRAY['Précision prévisions 94%', 'Réduction stocks 25%', 'Automatisation commandes'], 'Réduction stock 25%, +15% taux de service, optimisation cash flow 2M€');

-- DIGITAL AGENCY - Enrichir les services  
INSERT INTO products (scenario_id, name, description, pricing_starter, pricing_professional, pricing_enterprise, key_features, competitive_advantages, roi) VALUES
('digital-agency', 'Performance Marketing Platform', 'Plateforme marketing automation complète avec attribution multi-canal, optimisation budgets IA et personalisation 1:1 cross-device.', '3000€/mois', '10000€/mois', '35000€/mois', ARRAY['Attribution multi-canal', 'Optimisation budgets IA', 'Personnalisation 1:1', 'Cross-device tracking', 'Automation workflows'], ARRAY['Attribution précise vs last-click', 'Optimisation temps réel budgets', 'Expertise équipe 15+ ans'], 'ROI campaigns +180%, réduction CAC 40%'),
('digital-agency', 'Brand Intelligence Suite', 'Suite complète de veille marque et analyse sentiment avec monitoring réseaux sociaux, e-réputation et competitive intelligence.', '1500€/mois', '5000€/mois', '18000€/mois', ARRAY['Monitoring réseaux sociaux', 'Analyse sentiment IA', 'Veille concurrentielle', 'Alerts temps réel', 'Reporting executive'], ARRAY['Couverture 500+ sources', 'Sentiment analysis 96% précision', 'Expertise secteur'], 'Amélioration sentiment +45%, réaction crise 10x plus rapide'),
('digital-agency', 'Content Factory Platform', 'Plateforme de production de contenu à grande échelle avec IA générative, workflow collaboratif et distribution omnicanale.', '2000€/mois', '7000€/mois', '25000€/mois', ARRAY['IA générative contenu', 'Workflow collaboratif', 'Distribution omnicanale', 'Brand guidelines auto', 'Performance tracking'], ARRAY['Production 5x plus rapide', 'Cohérence brand garantie', 'Expertise créative'], 'Réduction coûts production 60%, +300% volume contenu'),
('digital-agency', 'CRO & UX Optimization Lab', 'Laboratoire d''optimisation conversion avec eye-tracking, tests utilisateurs automatisés et recommandations UX par IA.', '2500€/mois', '8000€/mois', '28000€/mois', ARRAY['Eye-tracking heatmaps', 'Tests utilisateurs auto', 'A/B testing avancé', 'Recommandations IA UX', 'Analytics comportementales'], ARRAY['Méthodologie scientifique', 'Tests 10x plus rapides', 'Expertise UX 12+ ans'], '+65% taux conversion, +40% satisfaction utilisateur');

-- CYBERSECURITY CONSULTING - Enrichir les services
INSERT INTO products (scenario_id, name, description, pricing_starter, pricing_professional, pricing_enterprise, key_features, competitive_advantages, roi) VALUES
('cybersecurity-consulting', 'Security Operations Center', 'SOC managé 24h/7j avec analysts experts, threat hunting proactif et réponse incidents automatisée pour PME/ETI.', '5000€/mois', '15000€/mois', '40000€/mois', ARRAY['Monitoring 24h/7j', 'Threat hunting proactif', 'Réponse incidents <30min', 'SIEM nouvelle génération', 'Compliance reporting'], ARRAY['Analysts seniors vs juniors', 'Threat hunting vs réactif', 'Réponse <30min vs 4h marché'], 'Réduction incidents 85%, temps résolution 90% plus rapide'),
('cybersecurity-consulting', 'Vulnerability Management Platform', 'Plateforme de gestion vulnérabilités avec scanning automatisé, priorisation par IA et orchestration remediation.', '2000€/mois', '8000€/mois', '25000€/mois', ARRAY['Scanning automatisé', 'Priorisation risque IA', 'Orchestration remediation', 'Dashboard executive', 'Compliance mapping'], ARRAY['Priorisation intelligente vs CVSS', 'Automatisation remediation', 'Faux positifs <5%'], 'Réduction surface attaque 70%, productivité équipes +120%'),
('cybersecurity-consulting', 'Zero Trust Architecture', 'Architecture Zero Trust complète avec micro-segmentation, authentification adaptative et monitoring comportemental continu.', '8000€/mois', '25000€/mois', '80000€/mois', ARRAY['Micro-segmentation réseau', 'Auth adaptative ML', 'Monitoring comportemental', 'Politique granulaire', 'Orchestration sécurité'], ARRAY['Approche holistique vs ponctuelle', 'ML comportemental avancé', 'Expertise Zero Trust'], 'Réduction risque breach 90%, compliance automatisée'),
('cybersecurity-consulting', 'Incident Response Platform', 'Plateforme de réponse incidents avec playbooks automatisés, forensics digitaux et communication crise intégrée.', '3000€/mois', '12000€/mois', '35000€/mois', ARRAY['Playbooks automatisés', 'Forensics digitaux', 'Communication crise', 'Evidence collection', 'Timeline reconstruction'], ARRAY['Automatisation vs manuel', 'Forensics experts certifiés', 'Temps réponse record'], 'Temps résolution incidents 80% plus rapide, coûts légaux -60%');

-- Continuer avec les autres scénarios...
-- KPI PERFORMANCE
INSERT INTO products (scenario_id, name, description, pricing_starter, pricing_professional, pricing_enterprise, key_features, competitive_advantages, roi) VALUES
('kpi-performance', 'Executive Dashboard Suite', 'Suite de dashboards executives temps réel avec KPIs prédictifs, alertes intelligentes et drill-down automatique pour dirigeants.', '1500€/mois', '6000€/mois', '20000€/mois', ARRAY['KPIs prédictifs ML', 'Dashboards temps réel', 'Alertes intelligentes', 'Drill-down automatique', 'Mobile executive app'], ARRAY['Prédiction vs rétrospectif', 'Alerts contextuelles intelligentes', 'UX dirigeants optimisée'], 'Gain temps décision 70%, amélioration performance 25%'),
('kpi-performance', 'Performance Analytics Engine', 'Moteur d''analytics performance avec corrélations automatiques, root cause analysis et recommandations actionables par IA.', '2000€/mois', '8000€/mois', '30000€/mois', ARRAY['Corrélations automatiques', 'Root cause analysis IA', 'Recommandations actionables', 'Modeling prédictif', 'What-if scenarios'], ARRAY['IA explicable vs black box', 'Recommandations actionables vs insights', 'Précision prédictions 94%'], 'Amélioration performance opérationnelle +35%, ROI décisions +180%'),
('kpi-performance', 'Data Governance Platform', 'Plateforme de gouvernance données avec lineage automatique, qualité données ML et conformité RGPD intégrée.', '1000€/mois', '4000€/mois', '15000€/mois', ARRAY['Data lineage automatique', 'Qualité données ML', 'Conformité RGPD', 'Catalog données intelligent', 'Access control granulaire'], ARRAY['Lineage automatique vs manuel', 'ML quality vs rules', 'RGPD by design'], 'Réduction temps préparation données 80%, conformité 100%'),
('kpi-performance', 'Business Intelligence Studio', 'Studio BI self-service avec NLP queries, auto-insights et collaboration temps réel pour démocratiser l''analytics.', '800€/mois', '3000€/mois', '12000€/mois', ARRAY['NLP queries naturelles', 'Auto-insights ML', 'Collaboration temps réel', 'Self-service BI', 'Visualisations adaptatives'], ARRAY['NLP français natif', 'Auto-insights vs static', 'Adoption utilisateurs 95%'], 'Démocratisation analytics, +200% utilisation BI, décisions data-driven +150%');

-- MANUFACTURING IOT
INSERT INTO products (scenario_id, name, description, pricing_starter, pricing_professional, pricing_enterprise, key_features, competitive_advantages, roi) VALUES
('manufacturing-iot', 'Predictive Maintenance Platform', 'Plateforme de maintenance prédictive IoT avec capteurs intelligents, ML algorithms et optimisation planning maintenance.', '5000€/mois', '20000€/mois', '80000€/mois', ARRAY['Capteurs IoT intelligents', 'ML maintenance prédictive', 'Optimisation planning', 'Digital twin machines', 'ROI calculator intégré'], ARRAY['Précision prédictions 96%', 'Installation plug-and-play', 'ROI garanti <18 mois'], 'Réduction downtime 75%, économies maintenance 40%, ROI 320% en 24 mois'),
('manufacturing-iot', 'Smart Factory Analytics', 'Analytics factory 4.0 avec optimisation flux production, quality control automatisé et traceabilité complète.', '3000€/mois', '15000€/mois', '50000€/mois', ARRAY['Optimisation flux temps réel', 'Quality control automatisé', 'Traceabilité bout-en-bout', 'OEE optimization', 'Energy management'], ARRAY['Optimisation temps réel vs batch', 'Quality ML vs inspection manuelle', 'Traceabilité blockchain'], '+25% productivité, +60% qualité, -30% rebuts'),
('manufacturing-iot', 'Supply Chain Intelligence', 'Intelligence supply chain avec tracking temps réel, prédiction disruptions et optimisation stocks multi-sites.', '2000€/mois', '10000€/mois', '35000€/mois', ARRAY['Tracking temps réel', 'Prédiction disruptions', 'Optimisation stocks multi-sites', 'Supplier risk scoring', 'Scenario planning'], ARRAY['Prédiction disruptions 90% précision', 'Optimisation multi-contraintes', 'Risk scoring automatique'], 'Réduction stocks 30%, amélioration service 20%, mitigation risques supply'],
('manufacturing-iot', 'Worker Safety & Productivity', 'Solution sécurité et productivité ouvriers avec wearables IoT, analytics comportementaux et prévention accidents.', '1500€/mois', '6000€/mois', '25000€/mois', ARRAY['Wearables IoT sécurité', 'Analytics comportementaux', 'Prévention accidents IA', 'Formation adaptative', 'Compliance automatique'], ARRAY['Prévention vs réaction', 'Wearables ergonomiques', 'Formation personnalisée'], 'Réduction accidents 80%, +15% productivité, conformité 100%');

-- SAAS HR TOOL
INSERT INTO products (scenario_id, name, description, pricing_starter, pricing_professional, pricing_enterprise, key_features, competitive_advantages, roi) VALUES
('saas-hr-tool', 'AI Recruitment Platform', 'Plateforme de recrutement IA avec screening automatisé, matching skills précis et prédiction performance candidats.', '500€/mois', '2000€/mois', '8000€/mois', ARRAY['Screening CV automatisé', 'Matching skills IA', 'Prédiction performance', 'Video interviews IA', 'Bias detection'], ARRAY['Matching 94% précision vs 60%', 'Bias reduction 80%', 'Temps recrutement 70% plus rapide'], 'Réduction temps recrutement 70%, amélioration qualité embauches +45%'),
('saas-hr-tool', 'Performance Management Suite', 'Suite gestion performance avec feedback 360° continu, goal tracking intelligent et plans développement personnalisés.', '300€/mois', '1200€/mois', '5000€/mois', ARRAY['Feedback 360° continu', 'Goal tracking intelligent', 'Plans développement IA', 'Pulse surveys automatiques', 'Analytics performance'], ARRAY['Feedback continu vs annuel', 'Personnalisation IA', 'Engagement +60%'], '+35% engagement collaborateurs, +25% performance équipes'),
('saas-hr-tool', 'Learning & Development Engine', 'Moteur d''apprentissage adaptatif avec personnalisation IA, microlearning et certification automatique skills.', '200€/mois', '800€/mois', '3000€/mois', ARRAY['Apprentissage adaptatif IA', 'Microlearning personnalisé', 'Certification skills auto', 'Learning paths intelligents', 'ROI formation tracking'], ARRAY['Personnalisation vs one-size-fits-all', 'Certification automatique', 'ROI formation mesurable'], '+180% efficacité formation, +90% rétention skills'),
('saas-hr-tool', 'People Analytics Platform', 'Plateforme analytics RH avec prédiction turnover, analytics diversité et optimisation workforce planning.', '400€/mois', '1500€/mois', '6000€/mois', ARRAY['Prédiction turnover ML', 'Analytics diversité', 'Workforce planning optimal', 'Predictive hiring', 'Compliance automatique'], ARRAY['Prédiction turnover 92% précision', 'Analytics éthiques transparentes', 'Workforce optimization'], 'Réduction turnover 40%, optimisation coûts RH 25%');

-- INDUSTRIAL MARKETPLACE
INSERT INTO products (scenario_id, name, description, pricing_starter, pricing_professional, pricing_enterprise, key_features, competitive_advantages, roi) VALUES
('industrial-marketplace', 'B2B Marketplace Platform', 'Marketplace B2B industrielle avec matching intelligent fournisseurs, négociation automatisée et financement intégré.', '2000€/mois', '8000€/mois', '30000€/mois', ARRAY['Matching intelligent fournisseurs', 'Négociation automatisée', 'Financement intégré', 'Quality scoring', 'Logistics optimization'], ARRAY['Matching 95% vs annuaires', 'Négociation automatisée', 'Financement one-stop'], '+40% économies achats, -60% temps sourcing'),
('industrial-marketplace', 'Supplier Network Intelligence', 'Intelligence réseau fournisseurs avec risk assessment, performance monitoring et diversification automatique.', '1500€/mois', '6000€/mois', '25000€/mois', ARRAY['Risk assessment continu', 'Performance monitoring', 'Diversification automatique', 'ESG scoring', 'Compliance tracking'], ARRAY['Risk scoring temps réel', 'ESG intégré natif', 'Diversification intelligente'], 'Réduction risques supply 70%, amélioration ESG score +50%'),
('industrial-marketplace', 'Procurement Analytics Suite', 'Suite analytics procurement avec spend analysis, contract intelligence et savings identification automatique.', '1000€/mois', '4000€/mois', '15000€/mois', ARRAY['Spend analysis avancée', 'Contract intelligence NLP', 'Savings identification auto', 'Price benchmarking', 'ROI procurement tracking'], ARRAY['NLP contrats vs lecture manuelle', 'Benchmarking temps réel', 'Savings automatique'], 'Identification savings +25%, optimisation contrats 90%'),
('industrial-marketplace', 'Quality Assurance Platform', 'Plateforme qualité fournisseurs avec audit automatisé, certification tracking et improvement plans IA.', '800€/mois', '3000€/mois', '12000€/mois', ARRAY['Audit automatisé', 'Certification tracking', 'Improvement plans IA', 'Quality scoring ML', 'Non-conformity management'], ARRAY['Audit automatisé vs manuel', 'Scoring qualité prédictif', 'Plans amélioration IA'], '+60% qualité fournisseurs, -50% non-conformités');