-- Enrichissement du scénario industrial-marketplace (PrecisionMetal Pro)
INSERT INTO interlocutors (scenario_id, name, role, personality, communication_style, decision_power, priorities, concerns, motivations, experience) VALUES
('industrial-marketplace', 'François Duranton', 'Directeur Général', 'Pragmatique et orienté résultats, exigeant sur la qualité', 'Direct et factuel', 'Décisionnaire final', ARRAY['Efficacité opérationnelle', 'Réduction des coûts', 'Qualité produits'], ARRAY['Disruption des processus', 'ROI incertain', 'Fiabilité fournisseurs'], ARRAY['Optimiser la supply chain', 'Maintenir la qualité', 'Croissance rentable'], '15 ans dans l''industrie métallurgique'),
('industrial-marketplace', 'Sylvie Marchand', 'Directrice Achats', 'Minutieuse et analytique, focus négociation', 'Structurée et détaillée', 'Influence forte sur décision', ARRAY['Négociation fournisseurs', 'Contrôle qualité', 'Optimisation coûts'], ARRAY['Perte de contrôle', 'Complexité plateforme', 'Formation équipes'], ARRAY['Centraliser les achats', 'Améliorer négociations', 'Simplifier processus'], '12 ans en achats industriels');

INSERT INTO products (scenario_id, name, description, pricing_starter, pricing_professional, pricing_enterprise, key_features, competitive_advantages, roi, implementation_time) VALUES
('industrial-marketplace', 'MetalConnect B2B', 'Marketplace B2B spécialisée dans les métaux de précision avec sourcing intelligent', '€3,500/mois - Jusqu''à 50 fournisseurs', '€8,500/mois - Jusqu''à 200 fournisseurs', '€18,000/mois - Fournisseurs illimités + API', ARRAY['Sourcing automatisé', 'Comparaison multi-critères', 'Négociation intégrée', 'Certification qualité', 'Analytics achats', 'Intégration ERP'], ARRAY['Spécialisation métallurgie', 'Base de 2000+ fournisseurs qualifiés', 'IA de matching avancée', 'Certification ISO intégrée'], '-15% coûts achats, -30% temps sourcing, +25% qualité', '6-8 semaines');

INSERT INTO swot_analyses (scenario_id, analysis_type, strengths, weaknesses, opportunities, threats) VALUES
('industrial-marketplace', 'product', '{"technology": "IA de matching fournisseurs", "expertise": "Spécialisation métallurgie", "network": "2000+ fournisseurs qualifiés"}', '{"cost": "Prix premium", "complexity": "Courbe d''apprentissage", "dependency": "Dépendance plateforme"}', '{"market": "Digitalisation industrie 4.0", "expansion": "Extension autres matériaux", "partnerships": "Partenariats intégrateurs"}', '{"competition": "Concurrents généralistes", "regulation": "Nouvelles réglementations", "economy": "Volatilité prix matières"}'),
('industrial-marketplace', 'company', '{"position": "Leader régional", "quality": "Réputation qualité", "experience": "40 ans d''expertise"}', '{"digital": "Retard digitalisation", "processes": "Processus manuels", "costs": "Coûts achats élevés"}', '{"efficiency": "Optimisation achats", "growth": "Nouveaux marchés", "innovation": "Innovation produits"}', '{"competition": "Concurrence asiatique", "supply": "Instabilité supply chain", "costs": "Inflation matières premières"}');