-- Enrichissement du scénario industrial-marketplace (PrecisionMetal Pro)
INSERT INTO interlocutors (scenario_id, name, role, personality, communication_style, decision_power, priorities, concerns, motivations, experience) VALUES
('industrial-marketplace', 'François Duranton', 'Directeur Général', 'Pragmatique et orienté résultats, exigeant sur la qualité', 'Direct et factuel', 'Décisionnaire final', ARRAY['Efficacité opérationnelle', 'Réduction des coûts', 'Qualité produits'], ARRAY['Disruption des processus', 'ROI incertain', 'Fiabilité fournisseurs'], ARRAY['Optimiser la supply chain', 'Maintenir la qualité', 'Croissance rentable'], '15 ans dans l''industrie métallurgique'),
('industrial-marketplace', 'Sylvie Marchand', 'Directrice Achats', 'Minutieuse et analytique, focus négociation', 'Structurée et détaillée', 'Influence forte sur décision', ARRAY['Négociation fournisseurs', 'Contrôle qualité', 'Optimisation coûts'], ARRAY['Perte de contrôle', 'Complexité plateforme', 'Formation équipes'], ARRAY['Centraliser les achats', 'Améliorer négociations', 'Simplifier processus'], '12 ans en achats industriels');

INSERT INTO products (scenario_id, name, description, pricing_starter, pricing_professional, pricing_enterprise, key_features, competitive_advantages, roi, implementation_time) VALUES
('industrial-marketplace', 'MetalConnect B2B', 'Marketplace B2B spécialisée dans les métaux de précision avec sourcing intelligent', '€3,500/mois - Jusqu''à 50 fournisseurs', '€8,500/mois - Jusqu''à 200 fournisseurs', '€18,000/mois - Fournisseurs illimités + API', ARRAY['Sourcing automatisé', 'Comparaison multi-critères', 'Négociation intégrée', 'Certification qualité', 'Analytics achats', 'Intégration ERP'], ARRAY['Spécialisation métallurgie', 'Base de 2000+ fournisseurs qualifiés', 'IA de matching avancée', 'Certification ISO intégrée'], '-15% coûts achats, -30% temps sourcing, +25% qualité', '6-8 semaines');

INSERT INTO swot_analyses (scenario_id, analysis_type, strengths, weaknesses, opportunities, threats) VALUES
('industrial-marketplace', 'product', '{"technology": "IA de matching fournisseurs", "expertise": "Spécialisation métallurgie", "network": "2000+ fournisseurs qualifiés"}', '{"cost": "Prix premium", "complexity": "Courbe d''apprentissage", "dependency": "Dépendance plateforme"}', '{"market": "Digitalisation industrie 4.0", "expansion": "Extension autres matériaux", "partnerships": "Partenariats intégrateurs"}', '{"competition": "Concurrents généralistes", "regulation": "Nouvelles réglementations", "economy": "Volatilité prix matières"}'),
('industrial-marketplace', 'company', '{"position": "Leader régional", "quality": "Réputation qualité", "experience": "40 ans d''expertise"}', '{"digital": "Retard digitalisation", "processes": "Processus manuels", "costs": "Coûts achats élevés"}', '{"efficiency": "Optimisation achats", "growth": "Nouveaux marchés", "innovation": "Innovation produits"}', '{"competition": "Concurrence asiatique", "supply": "Instabilité supply chain", "costs": "Inflation matières premières"}');

-- Enrichissement du scénario saas-hr-tool (TechGrow Solutions)
INSERT INTO interlocutors (scenario_id, name, role, personality, communication_style, decision_power, priorities, concerns, motivations, experience) VALUES
('saas-hr-tool', 'Émilie Rousseau', 'Directrice RH', 'Empathique mais exigeante, focus employee experience', 'Collaborative et inspirante', 'Décisionnaire avec CEO', ARRAY['Attraction talents', 'Rétention équipes', 'Performance RH'], ARRAY['Adoption utilisateurs', 'Complexité outil', 'Budget limité'], ARRAY['Optimiser processus RH', 'Améliorer satisfaction', 'Croissance équipe'], '8 ans en RH tech scale-up'),
('saas-hr-tool', 'Nicolas Petit', 'CTO', 'Technique et sécuritaire, focus intégration', 'Précis et structuré', 'Validation technique obligatoire', ARRAY['Sécurité données', 'Intégrations', 'Performance'], ARRAY['Sécurité RGPD', 'APIs instables', 'Maintenance'], ARRAY['Stack tech cohérent', 'Sécurité maximale', 'Évolutivité'], '10 ans développement SaaS');

INSERT INTO products (scenario_id, name, description, pricing_starter, pricing_professional, pricing_enterprise, key_features, competitive_advantages, roi, implementation_time) VALUES
('saas-hr-tool', 'TalentFlow Pro', 'Suite RH complète avec IA pour scale-ups en croissance rapide', '€25/utilisateur/mois - Jusqu''à 50 employés', '€45/utilisateur/mois - Jusqu''à 200 employés', '€75/utilisateur/mois - Illimité + support', ARRAY['Recrutement IA', 'Onboarding automatisé', 'Performance management', 'Analytics RH', 'Mobile-first', 'API complète'], ARRAY['Spécialisé scale-ups tech', 'IA de matching candidats', 'Onboarding en 24h', 'Conformité RGPD native'], '-40% temps recrutement, +60% rétention, +35% satisfaction employés', '3-4 semaines');

INSERT INTO swot_analyses (scenario_id, analysis_type, strengths, weaknesses, opportunities, threats) VALUES
('saas-hr-tool', 'product', '{"ai": "IA recrutement avancée", "ux": "Interface intuitive", "mobile": "Mobile-first design"}', '{"price": "Prix mid-market", "features": "Fonctionnalités avancées complexes", "support": "Support en anglais"}', '{"market": "Boom scale-ups", "remote": "Travail hybride", "ai": "IA générative RH"}', '{"competition": "Giants RH", "regulation": "RGPD évolutif", "economy": "Ralentissement recrutement"}'),
('saas-hr-tool', 'company', '{"growth": "Croissance 300% annuelle", "team": "Équipe talentueuse", "culture": "Culture innovation"}', '{"hr": "Processus RH manuels", "time": "Temps recrutement élevé", "retention": "Turnover croissant"}', '{"scale": "Scaling rapide", "international": "Expansion Europe", "product": "Innovation produit"}', '{"talent": "Guerre des talents", "costs": "Inflation salariale", "competition": "Concurrence startup"}';