-- Produits cybersecurity-consulting
INSERT INTO products (scenario_id, name, description, pricing_starter, pricing_professional, pricing_enterprise, key_features, competitive_advantages, roi, implementation_time) VALUES
('cybersecurity-consulting', 'SecureBank DORA', 'Suite de conseil cybersécurité bancaire pour conformité DORA', '€25,000 - Audit initial + roadmap', '€75,000 - Audit + mise en conformité', '€150,000 - Audit + conformité + monitoring', ARRAY['Audit sécurité complet', 'Conformité DORA', 'Plan remediation', 'Formation équipes', 'Monitoring continu', 'Support 24/7'], ARRAY['Expertise bancaire 15 ans', 'Certification DORA', 'Méthodologie éprouvée', 'Équipe dédiée secteur bancaire'], 'Conformité 100%, -80% risque cyber, évitement pénalités', '3-6 mois selon périmètre');

-- SWOT cybersecurity-consulting  
INSERT INTO swot_analyses (scenario_id, analysis_type, strengths, weaknesses, opportunities, threats) VALUES
('cybersecurity-consulting', 'product', '{"expertise": "15 ans expertise bancaire", "certification": "Certification DORA officielle", "methodology": "Méthodologie éprouvée"}', '{"cost": "Investissement important", "duration": "Projet long terme", "resources": "Mobilisation équipes"}', '{"regulation": "Obligation DORA 2025", "market": "Digitalisation bancaire", "trust": "Confiance renforcée"}', '{"competition": "Grands cabinets", "timeline": "Délais serrés DORA", "complexity": "Complexité réglementaire"}'),
('cybersecurity-consulting', 'company', '{"reputation": "Banque de confiance", "client": "Base client fidèle", "regional": "Ancrage territorial"}', '{"cyber": "Vulnérabilités cyber", "compliance": "Retard conformité", "resources": "Ressources IT limitées"}', '{"dora": "Mise en conformité DORA", "digital": "Transformation digitale", "trust": "Renforcement confiance"}', '{"cyber": "Cyberattaques croissantes", "regulation": "Durcissement réglementaire", "competition": "Fintech agiles"}');

-- Enrichissement byss-vns-school (ESCAP)
INSERT INTO interlocutors (scenario_id, name, role, personality, communication_style, decision_power, priorities, concerns, motivations, experience) VALUES
('byss-vns-school', 'Paul Leclerc', 'Directeur Général', 'Visionnaire et pragmatique, orienté innovation pédagogique', 'Inspirant et stratégique', 'Décisionnaire final', ARRAY['Innovation pédagogique', 'Attractivité école', 'ROI formation'], ARRAY['Coût investissement', 'Adoption enseignants', 'Efficacité réelle'], ARRAY['Moderniser enseignement', 'Différenciation concurrentielle', 'Employabilité étudiants'], '25 ans dans l''enseignement supérieur'),
('byss-vns-school', 'Isabelle Moreau', 'Directrice Pédagogique', 'Exigeante sur qualité, focus résultats étudiants', 'Structurée et bienveillante', 'Influence forte programmes', ARRAY['Qualité pédagogique', 'Résultats étudiants', 'Innovation enseignement'], ARRAY['Complexité outil', 'Formation enseignants', 'Résistance changement'], ARRAY['Améliorer pédagogie', 'Moderniser méthodes', 'Réussite étudiants'], '18 ans en direction pédagogique');