-- Enrichissement du scénario saas-hr-tool (TechGrow Solutions)
INSERT INTO interlocutors (scenario_id, name, role, personality, communication_style, decision_power, priorities, concerns, motivations, experience) VALUES
('saas-hr-tool', 'Émilie Rousseau', 'Directrice RH', 'Empathique mais exigeante, focus employee experience', 'Collaborative et inspirante', 'Décisionnaire avec CEO', ARRAY['Attraction talents', 'Rétention équipes', 'Performance RH'], ARRAY['Adoption utilisateurs', 'Complexité outil', 'Budget limité'], ARRAY['Optimiser processus RH', 'Améliorer satisfaction', 'Croissance équipe'], '8 ans en RH tech scale-up'),
('saas-hr-tool', 'Nicolas Petit', 'CTO', 'Technique et sécuritaire, focus intégration', 'Précis et structuré', 'Validation technique obligatoire', ARRAY['Sécurité données', 'Intégrations', 'Performance'], ARRAY['Sécurité RGPD', 'APIs instables', 'Maintenance'], ARRAY['Stack tech cohérent', 'Sécurité maximale', 'Évolutivité'], '10 ans développement SaaS');

INSERT INTO products (scenario_id, name, description, pricing_starter, pricing_professional, pricing_enterprise, key_features, competitive_advantages, roi, implementation_time) VALUES
('saas-hr-tool', 'TalentFlow Pro', 'Suite RH complète avec IA pour scale-ups en croissance rapide', '€25/utilisateur/mois - Jusqu''à 50 employés', '€45/utilisateur/mois - Jusqu''à 200 employés', '€75/utilisateur/mois - Illimité + support', ARRAY['Recrutement IA', 'Onboarding automatisé', 'Performance management', 'Analytics RH', 'Mobile-first', 'API complète'], ARRAY['Spécialisé scale-ups tech', 'IA de matching candidats', 'Onboarding en 24h', 'Conformité RGPD native'], '-40% temps recrutement, +60% rétention, +35% satisfaction employés', '3-4 semaines');

INSERT INTO swot_analyses (scenario_id, analysis_type, strengths, weaknesses, opportunities, threats) VALUES
('saas-hr-tool', 'product', '{"ai": "IA recrutement avancée", "ux": "Interface intuitive", "mobile": "Mobile-first design"}', '{"price": "Prix mid-market", "features": "Fonctionnalités avancées complexes", "support": "Support en anglais"}', '{"market": "Boom scale-ups", "remote": "Travail hybride", "ai": "IA générative RH"}', '{"competition": "Giants RH", "regulation": "RGPD évolutif", "economy": "Ralentissement recrutement"}'),
('saas-hr-tool', 'company', '{"growth": "Croissance 300% annuelle", "team": "Équipe talentueuse", "culture": "Culture innovation"}', '{"hr": "Processus RH manuels", "time": "Temps recrutement élevé", "retention": "Turnover croissant"}', '{"scale": "Scaling rapide", "international": "Expansion Europe", "product": "Innovation produit"}', '{"talent": "Guerre des talents", "costs": "Inflation salariale", "competition": "Concurrence startup"}');

-- Enrichissement du scénario cybersecurity-consulting (Banque Régionale Loire)
INSERT INTO interlocutors (scenario_id, name, role, personality, communication_style, decision_power, priorities, concerns, motivations, experience) VALUES
('cybersecurity-consulting', 'Jean-Claude Moreau', 'DSI', 'Prudent et méthodique, expert technique', 'Technique et précis', 'Décisionnaire final', ARRAY['Sécurité maximale', 'Conformité réglementaire', 'Continuité activité'], ARRAY['Coût consultant', 'Disruption système', 'Risque projet'], ARRAY['Sécuriser infrastructure', 'Conformité DORA', 'Modernisation IT'], '20 ans en IT bancaire'),
('cybersecurity-consulting', 'Marie-Claire Dubost', 'Directrice Risques', 'Rigoureuse et réglementaire, risk-averse', 'Formelle et structurée', 'Influence forte validation', ARRAY['Conformité totale', 'Audit réussi', 'Réputation banque'], ARRAY['Non-conformité', 'Pénalités régulateur', 'Réputation'], ARRAY['Conformité DORA', 'Réduction risques', 'Audit sans faille'], '15 ans en risk management bancaire');