// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rcfczlwyywaiovxfgdzs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjZmN6bHd5eXdhaW92eGZnZHpzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxNDgwOTMsImV4cCI6MjA3MTcyNDA5M30.ggRhNBF6JjLqKLftkFJpEVUAjbP4uufYGjLn-PdEoEo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});